# Copyright (c) 2025 Jonathan Poulin (EmbedTux)
#
# SPDX-License-Identifier: MIT
#

'''
BitBake 'Fetch' implementations

This implementation is for flutter pub cache. It act as a dummy fetcher
as the pub spec cache package is generated by the archive_pub_cache task
of the flutter-app bbclass. It allow the restore_pub_cache task to gather
the package in the download folder or from the download pre-mirror.

PREMIRRORS must be set with the following line (note the terminal "/PATH"):

    PREMIRROR_append = "pubcache://.*/?.*    <MIRROR_URL>/PATH"

example:

    PREMIRROR_append = "pubcache://.*/?.*    file://path/to/your/mirror/PATH"
    PREMIRROR_append = "pubcache://.*/?.*    https://my.mirror.org/download/PATH"

Note:
      This fetcher doesn't support checksum to allow archive_pub_cache to
      easily generate the .done file.
      The "/PATH" must be added for this fetcher because it doesn't support
      checksum.
      Do understand this condition but this is cause be this line
      "elif ud.localpath and ud.method.supports_checksum(ud):"
      in function uri_replace of bitbake/lib/bb/fetch2/__init__.py
'''

import os
import urllib.parse
from bb.fetch2 import FetchMethod

import logging
logger = logging.getLogger("BitBake.Fetcher")

class PUB_CACHE(FetchMethod):
    '''Class to fetch a flutter pub cache archive'''

    def supports(self, ud, d):
        """
        Check to see if a given url can be fetched with pub_cache.
        """
        return ud.type in ['pubcache']

    def supports_checksum(self, ud):
        return False

    def urldata_init(self, ud, d):
        ud.localfile = d.expand(os.path.basename(os.path.normpath(urllib.parse.unquote(ud.url))))

    def download(self, ud, d):
        pass
